### ISSUE TITLE
v0.4.0 on npm is badly published

### ISSUE THREAD

**Issue by PabloSzx** [aerogear/graphql-query-mapper#21]
![Code_-_Insiders_OKeaIaYuEQ](https://user-images.githubusercontent.com/8672915/87743146-4abb8500-c7b6-11ea-917d-ba4fd95379bc.png)

The type definitions are not published and are nowhere to be seen, and TypeScript can't do anything about it:

![image](https://user-images.githubusercontent.com/8672915/87743243-7c345080-c7b6-11ea-956c-ce8185b71e5d.png)

**Comment by wtrocki** [comment]
```
[wtrocki@typeapi graphql-query-mapper (master ✗)]$ npm publish            
npm notice 
npm notice 📦  @aerogear/graphql-query-mapper@0.4.1
npm notice === Tarball Contents === 
npm notice 11.4kB  LICENSE                                  
npm notice 108.8kB resources/animation.gif                  
npm notice 258B    dist/index.js                            
npm notice 1.6kB   example/index.js                         
npm notice 915B    dist/QueryFields.js                      
npm notice 2.4kB   dist/QueryObject.js                      
npm notice 1.5kB   dist/SelectionSetParser.js               
npm notice 5.6kB   tests/mocks/infoBasic.json               
npm notice 6.4kB   tests/mocks/infoFragment.json            
npm notice 8.0kB   tests/mocks/infoInline.json              
npm notice 488B    .vscode/launch.json                      
npm notice 1.5kB   package.json                             
npm notice 82B     renovate.json                            
npm notice 698B    tsconfig.json                            
npm notice 766B    tslint.json                              
npm notice 129B    dist/index.js.map                        
npm notice 545B    dist/QueryFields.js.map                  
npm notice 1.5kB   dist/QueryObject.js.map                  
npm notice 1.2kB   dist/SelectionSetParser.js.map           
npm notice 99B     .github/CONTRIBUTING.md                  
npm notice 122B    example/README.md                        
npm notice 4.2kB   README.md                                
npm notice 10.0kB  resources/logo.png                       
npm notice 742B    example/migrations/001-initial-schema.sql
npm notice 16.4kB  example/database.sqlite                  
npm notice 61B     src/index.ts                             
npm notice 790B    src/QueryFields.ts                       
npm notice 2.6kB   src/QueryObject.ts                       
npm notice 716B    tests/QueryObjectTests.ts                
npm notice 1.5kB   src/SelectionSetParser.ts                
npm notice 1.1kB   .circleci/config.yml                     
npm notice === Tarball Details === 
npm notice name:          @aerogear/graphql-query-mapper          
npm notice version:       0.4.1                                   
npm notice package size:  129.1 kB                                
npm notice unpacked size: 191.9 kB                                
npm notice shasum:        a4752f148b4f8cac12efb6595614103fd2f9b1d9
npm notice integrity:     sha512-04enDlHgEhsxv[...]NHU8w22F3JoVA==
npm notice total files:   31                                      
npm notice 
+ @aerogear/graphql-query-mapper@0.4.1
```

**Comment by wtrocki** [comment]
Thanks for catching this! 
I have done a fresh release that includes types

[wtrocki@typeapi graphql-query-mapper (master ✗)]$ npm publish            
npm notice 
npm notice 📦  @aerogear/graphql-query-mapper@0.4.2
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE                       
npm notice 258B   dist/index.js                 
npm notice 915B   dist/QueryFields.js           
npm notice 2.4kB  dist/QueryObject.js           
npm notice 1.5kB  dist/SelectionSetParser.js    
npm notice 1.5kB  package.json                  
npm notice 82B    renovate.json                 
npm notice 698B   tsconfig.json                 
npm notice 766B   tslint.json                   
npm notice 129B   dist/index.js.map             
npm notice 545B   dist/QueryFields.js.map       
npm notice 1.5kB  dist/QueryObject.js.map       
npm notice 1.2kB  dist/SelectionSetParser.js.map
npm notice 4.2kB  README.md                     
npm notice 62B    types/index.d.ts              
npm notice 61B    src/index.ts                  
npm notice 483B   types/QueryFields.d.ts        
npm notice 790B   src/QueryFields.ts            
npm notice 1.6kB  types/QueryObject.d.ts        
npm notice 2.6kB  src/QueryObject.ts            
npm notice 622B   types/SelectionSetParser.d.ts 
npm notice 1.5kB  src/SelectionSetParser.ts     
npm notice === Tarball Details === 
npm notice name:          @aerogear/graphql-query-mapper          
npm notice version:       0.4.2                                   
npm notice package size:  10.1 kB                                 
npm notice unpacked size: 34.7 kB                                 
npm notice shasum:        c2514ce2770118739073cf7018034237b7424b36
npm notice integrity:     sha512-tRMdoyfAz/CoA[...]fMzJYNzvx6sHQ==
npm notice total files:   22                                      
npm notice 
+ @aerogear/graphql-query-mapper@0.4.2

**Comment by wtrocki** [comment]
Thank you so much for the logging issue and sorry for breaking the package.
All should work now. If you experience further issues feel free to reopen issue

**Comment by PabloSzx** [comment]
@wtrocki thanks for the quick response, and nice project 👍
